version: '3'

services:
    db:
        image: 'postgres:12.3'
        volumes: 
            - 'postgres:/var/lib/postgresql/data'
        environment: 
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - 5432:5432
    
    test:
        depends_on:
            - 'db'
            - 'box'
            - 'selenium'
        build: .
        command: bash start.sh
        ports: 
            - '3000:3000'
        volumes: 
            - '.:/DevOneBitCode'
            - 'box:/box'
        environment: 
            - BUNDLE_PATH=/box
            - DB_HOST=db
            - DB_USER=postgres
            - DB_PASS=postgres
            - SELENIUM_HOST=selenium
            - SELENIUM_PORT=4444
            - TEST_APP_HOST=test
            - TEST_PORT=3000
            - RAILS_ENV=test
        stdin_open: true
        tty: true

    box:
        image: busybox
        volumes: 
            - box:/box
    
    selenium:
        image: selenium/standalone-chrome-debug:3.0.1-germanium
        logging: 
            driver: none
        stdin_open: true
        tty: true
        ports: 
            - '4444:4444'
            - '5900:5900'

volumes: 
    postgres:
    box: