version: '3'

services:
    db:
        image: 'postgres:12.3'
        volumes: 
            - 'postgres:/var/lib/postgresql/data'
        environment: 
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - 5432:5432
    
    app:
        depends_on:
            - 'db'
            - 'box'
        build: .
        command: bash start.sh
        ports: 
            - '3000:3000'
        volumes: 
            - '.:/DevOneBitCode'
            - 'box:/box'
        environment: 
            - BUNDLE_PATH=/box
            - DB_HOST=db
            - DB_USER=postgres
            - DB_PASS=postgres
        stdin_open: true
        tty: true

    box:
        image: busybox
        volumes: 
            - box:/box

    mailcacther:
        image: tophfr/mailcacther
        ports: 
            - 1025:25
            - 1080:80

volumes: 
    postgres:
    box: